# @package _global_

eval_dataset_name: "deepwind_eval"

data_val:
  npy_root: "/scratch/pawsey0115/hwang4/deepwindData/test2"
  metadata_path: "/scratch/pawsey0115/hwang4/deepwindData/train_metadata.csv"

  context_length: ${model.context_length}
  stride: 512
  max_vars: 6
  pad_val_id: 10
