# @package _global_

training:
  max_steps: 50
  warmup_steps: 0
  logging_steps: 1
  save_steps: 25
  
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1

  bf16: false
  fp16: false

  dataloader_num_workers: 0

  report_to: "none"
  use_cpu: true

  output_dir: "${hydra:runtime.cwd}/debug_checkpoints/${run_name}"

  evaluation_strategy: "steps"
  eval_steps: 25
  per_device_eval_batch_size: 16
  load_best_model_at_end: true
  metric_for_best_model: "loss"
  greater_is_better: false
  prediction_loss_only: true

  overwrite_output_dir: true
