# @package _global_

training:
  # --- Checkpointing & Logging ---
  output_dir: "/scratch/pawsey0115/hwang4/deepwind_experiments/checkpoints/${run_name}"
  overwrite_output_dir: false
  run_name: ${run_name}
  report_to: "wandb"

  # --- Optimization ---
  learning_rate: 3e-4
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  max_grad_norm: 1.0

  # --- Batch Size & Steps ---
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 2
  ignore_data_skip: false

  # max_steps: 50000 
  num_train_epochs: 10

  lr_scheduler_type: "cosine"
  warmup_ratio: 0.03

  # --- Hardware & Precision ---
  bf16: true
  dataloader_num_workers: 8
  dataloader_pin_memory: true

  # --- Saving Strategy ---
  save_strategy: "epoch"   
  # save_steps: 2000       # <--- 在 "epoch" 模式下此参数无效

  save_total_limit: 5

  # --- Logging Strategy ---
  # 日志依然可以按步数打印，方便观察 Loss 曲线
  logging_strategy: "steps"
  logging_steps: 50
  logging_first_step: true
  disable_tqdm: true

  # --- DDP Settings ---
  ddp_find_unused_parameters: true

  # --- Evaluation Strategy ---
  # [修改点 2] 改为每个 Epoch 结束测一次
  eval_strategy: "epoch"
  # eval_steps: 500        # <--- 在 "epoch" 模式下此参数无效
  
  per_device_eval_batch_size: 16
  load_best_model_at_end: true
  metric_for_best_model: "loss"
  greater_is_better: false
  prediction_loss_only: true
  log_on_each_node: false
  